[package]
name = "yottaclock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
axum = { version = "0.5.17", features = ["headers", "form"] }
chrono = { version = "0.4.23", features = ["serde", "clock", "std", "wasmbind"], default-features = false }
chrono-tz = "0.8.0"
dotenvy = "0.15.6"
futures = "0.3.25"
rand = "0.8.5"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.147", features = ["derive"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres", "chrono"] }
thiserror = "1.0.37"
tokio = { version = "1.22.0", features = ["full"] }
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
